### ISSUE TITLE
关于时间节点

### ISSUE THREAD

**Issue by taseikyo** [Writeup001/weibo_Hot_Search#3]
看 README 上写是一天爬两次，早晚 11 点，然后看代码也是一次运行
感觉这样会漏掉不少“热点”，因为有时候热搜会突然出现，然后因为某些原因不见了
所以建议可以弄个定时器，隔一个小时或者两个小时爬一次，避免漏掉”热点“ 😏

**Comment by Writeup001** [comment]
README 上是写的是一天爬两次，但是代码上写的是一次运行。是因为我用的 Linux 的 Crontab 设置的计划任务，所以我只需要在 Linux 服务器上设置运行次数即可。:sunglasses:

**Comment by taseikyo** [comment]
也对 用 crontab 设置定时任务无需手动跑 😝
